### ISSUE TITLE
Complete the SuperBIT OBA module before the launch window

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#123]
As the title says - the launch window opens on March 21st. As this will be accompanied by a software-freeze on the telescope's computer, we should finalize the OBA before this date. To minimize the size of the repo on the onboard computer, we will likely create a tag and then fork the repo with all modules other than OBA and utility functionality (& the CookieCutter of course!) removed.

Issues that need to be solved before then:

- [x] Use realistic rolls between bands in sims
- [x] Compute PSF aberrations for all filters (#103)
- [x] Add "inactive pixels" to the calibration mask (#108)
- [x] On-the-fly masking configuration (#114)
- [x] Astrometry failures & backups (#115)
- [x] Add WCS to (copied) RAW science images (#116)
- [x] Pass mask to La Cosmic (#117)
- [x] La Cosmic (or alternative) speedups (#119)
- [x] ~~Add relative flux weights for the detection image~~
- [x] Handle `NoOverlap`'s in the CookieCutter (#118)
- [x] Bright star masking (#120)
- [x] Use estimated BKG noise instead of predicted during star masking
- [x] Determining max bounding box for OBA coadds (#121)
- [x] Add cluster member galaxies to the OBA sims (#122)
- [x] Finish CookieCutter mask implementation (#124)
- [x] Write CookieCutter to Image method (and test on MEDS) (#126)
- [x] Save over any desired calibrated image file HDR fields to the copied RAW's for CookieCutter
- [x] Add cluster center option for CookieCutter (#125)
- [x] Make final `oba` conda env (mostly done, but need to finalize minimal version)
- [x] Either new script or incorporate sufficient image checker into `run_oba.py`
- [x] Default the `cleanup` module to remove `OBA_TEMP` dir
- [x] OBA base config + key:val replacement command
- [x] OBA prepper / run command (`target_name`, `band:req_num`); `det_bands` in base config
- [x] Update expected FITS header cols to match new QCC definitions
- [x] SExtractor not running detection on full image (#127)
- [x] Significantly speedup `CookieCutter`
- [x] Figure out the `CookieCutter` WCS inconsistency #128 
- [x] Implement second "2D" `CookieCutter` output mode
- [x] Speedup "2D" `CookieCutter`
- [ ] Validate stellar masking
- [ ] Finalize config values
- [x] Write QCC OBA script to update a swarp/sextractor config
- [x] Do `IMG_QUAL` parsing in `preprocess` (#130)
- [x] Rework `prep_oba.py` to handle new `IMG_QUAL` parsing (#130)
- [x] Incorporate Steve's GAIA cats into star masking (#120)
- [x] Solve weird noise stripes when using `COMBINE_TYPE: CLIPPED`
- [x] Fix coadd clipping for bands not in det image
- [x] Add band-dependence on flat images in `IOManager`
- [x] Add saturation bitmask flag
- [x] Update QCC uniform flats for all bands
- [x] Deeper GAIA cat to mag 15
- [x] Update Starmasking spike scaling
- [ ] Brightest star not masked?
- [x] Speedup 2D CC writing
- [x] Change output format (no dirs)
- [ ] Reset qcc global OBA config after testing
- [ ] Check what is happening w/ COW command on `bands`, if time
- [ ] Remove final warnings

Right before flight:
- [x] Clear out OBA dirs on QCC
- [x] Final `git pull`'s and tests
- [ ] Tag GitHub version

Will update & add as we go (though issues won't technically close until merged into `master`)
