### ISSUE TITLE
Finish all required updates for final Gauss PSF run

### ISSUE THREAD

**Issue by sweverett** [superbit-collaboration/superbit-metacal#79]
We will use this issue to keep track of all things that need to be completed before we start our final Gauss PSF run.

TODO:

- [x] Create per-exposure weight & mask extensions for the SCI images (#10, #75)
- [x] Create segmentation maps w/ SExtractor (#75, #77) and...
- [x] ...use them to make per-stamp masks for MEDS (#75, #77)
- [x] Update mcal selections & correctly cut out foreground sources (#71)
- [x] Update input catalog (#67)
- [x] Update mcal & ngmix-fit to use `ngmix v2.X` for new API & method improvements (#78)
- [x] Add PIFF and mcal seeds (#66, #78)
- [x] #85
- [x] #89 
- [x] #90  
- [ ] #92 
- [ ] #94 
- [ ] #95
